### ISSUE TITLE
please change rx_permission => rx.permission

### ISSUE THREAD

**Issue by roshanman** [sunshinejr/RxPermission#11]
this is swift3 style for rxswift

**Comment by sunshinejr** [comment]
@roshanman Will see if it is possible and what can we do! Thanks for the proposition! 🙇

**Comment by sunshinejr** [comment]
So I was trying it out and it seems we can do it by extending `Reactive<Base>` protocol of RxSwift, so great on that part! However, we have to unfortunately wait till `Permission` is released (at least for beta stage). As of now the code for the release is prepared in the main repo and waiting, so I will keep an eye on that 🐼
