### ISSUE TITLE
Code style is not perfect

### ISSUE THREAD

**Issue by roshanman** [sunshinejr/RxPermission#16]
I think this will be better.

``` swift
Permission.rx.contacts
    .subscribeNext { status in
        print("Status: \(status)")
    }
    .addDisposableTo(disposeBag)
```

**Comment by AndrewSB** [comment]
That seems to be an issue with the underlying Permission library we're using. Both `Permission` and `Permission.contacts` are of type `Permission`, so it isn't possible to compose that without making changes in @delba's library

**Comment by roshanman** [comment]
How about this ?

``` swift
extension Permission {
    static var rx:Permission.Type {
        return Permission.self
    }
}

Permission.rx.contacts
    .subscribeNext { status in
        print("Status: \(status)")
    }
    .addDisposableTo(disposeBag)
```

**Comment by AndrewSB** [comment]
In tandem or instead of?

**Comment by roshanman** [comment]
Just make the code similar with RxSwift.
eg. button.rx.tap

**Comment by AndrewSB** [comment]
I think this makes sense. Can you make a pull request so @sunshinejr can review?
