### ISSUE TITLE
Please update to swift 3 and RxSwift 3.0

### ISSUE THREAD

**Issue by zayats77** [sunshinejr/RxPermission#19]
- `RxSwift (~> 3.0)` required by `Podfile`
- `RxSwift (= 3.0.0-beta.1)` required by `RxPermission (1.0.0-beta.2)`

**Comment by AndrewSB** [comment]
@zayats77: can you make a pull request implementing your change?
I usually use Carthage, so I'm not very familiar with cocoapods

**Comment by sunshinejr** [comment]
Sorry for the delay 😞 The newest release 1.0.0 should work correctly with newest versions of RxSwift & Permission. If you find an error please make another issue. Thanks!
